image_width: 1280
image_height: 720
camera_name: head_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [2247.44118,    0.     ,  700.14658,
            0.     , 2249.66809,  283.54688,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.985777, -1.012917, -0.048107, 0.024875, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2430.61523,    0.     ,  705.07485,    0.     ,
            0.     , 2423.55591,  271.83043,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
