image_width: 1280
image_height: 720
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [3646.63567,    0.     ,  595.43292,
            0.     , 3633.39776,  337.49575,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [2.862341, 7.824394, -0.027223, -0.071754, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [4013.33374,    0.     ,  582.33472,    0.     ,
            0.     , 4027.58301,  333.82765,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
